/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#00734d",
        "tertiary-fixed": "#cee9d3",
        "tertiary-container": "#2a4131",
        "on-primary-fixed": "#002114",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#092012",
        "surface-bright": "#f9f9ff",
        "surface-container-high": "#dee8ff",
        "secondary-fixed-dim": "#75daa8",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#93ad98",
        "outline": "#717973",
        "inverse-primary": "#a5d0b9",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "surface-container": "#e7eeff",
        "primary-container": "#1b4332",
        "on-surface": "#121c2c",
        "tertiary-fixed-dim": "#b3cdb7",
        "on-secondary-fixed-variant": "#005235",
        "inverse-surface": "#273141",
        "surface-tint": "#3f6653",
        "primary-fixed": "#c1ecd4",
        "surface": "#f9f9ff",
        "on-primary-container": "#86af99",
        "background": "#f9f9ff",
        "on-secondary-fixed": "#002113",
        "on-background": "#121c2c",
        "secondary-fixed": "#92f7c3",
        "surface-variant": "#d9e3f9",
        "primary": "#012d1d",
        "on-surface-variant": "#414844",
        "surface-container-highest": "#d9e3f9",
        "on-tertiary-fixed-variant": "#354c3b",
        "surface-container-low": "#f0f3ff",
        "secondary": "#006c48",
        "primary-fixed-dim": "#a5d0b9",
        "surface-dim": "#d0daf0",
        "outline-variant": "#c1c8c2",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#274e3d",
        "tertiary": "#152b1c",
        "secondary-container": "#92f7c3",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#ebf1ff"
      },
      fontFamily: {
        "display-hero": ["Space Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "label-lg": ["JetBrains Mono", "monospace"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "body-sm": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"]
      },
      spacing: {
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "margin-mobile": "1.25rem",
        "gutter": "1.5rem",
        "space-lg": "1.5rem",
        "gutter-mobile": "0.75rem",
        "space-xl": "2.5rem",
        "space-sm": "0.5rem",
        "margin": "3rem"
      }
    },
  },
  plugins: [],
}
